"""Serialize a separately bound, explicitly authored primary review of claims 019-059."""
import gzip
import hashlib
import json
import sys
from pathlib import Path

from ges.core import digest
from ges.semantics import stable_id, validate_record

OUT = Path(__file__).resolve().parent
ROOT = OUT.parents[3]
CACHE = Path(sys.argv[1])
sha = lambda b: hashlib.sha256(b).hexdigest()
assignment_path = ROOT / 'evidence/wave-20261009/assignment.json'
a = json.loads(assignment_path.read_bytes())
catalog = json.loads((ROOT / 'controls/catalog.json').read_bytes())
proposals = json.loads((ROOT / 'controls/review_queue.json').read_bytes())
ci = {c['id']: c for c in catalog}
pi = {c['id']: c for c in proposals}
crosswalk_path = OUT.parent / 'occurrence-crosswalk.json'
subjects = {c['claim']['claim_id']: c for c in json.loads(crosswalk_path.read_bytes())}
snapshot_path = CACHE / 'sources/github__github-well-architected.text.jsonl.gz'
rows = {r['path']: r for r in map(json.loads, gzip.open(snapshot_path, 'rt'))}
source = rows['content/library/application-security/checklist.md']
assert sha(source['content'].encode()) == 'd460c2c2daf45d6914cc15b908f1e487d0e4afe8e28632706b58ccddaab27773'

# Each row is an accountable judgment authored against pinned source lines,
# original claim wording, and the full related draft objective/acceptance.
# No keyword-based routing and no mechanically accepted source expression.
judgments = [
 ('GES-IAM-004', 'List the regulations and standards applicable to the organization; GDPR and HIPAA are examples, not universal applicability. The draft identifies external obligations but must expose the maintained list and avoid hiding applicability discovery behind an already-regulated profile.', 'organization; applicability discovery and obligation inventory', None),
 ('GES-IAM-004', 'Actual conformity with applicable regulations and standards is distinct from identifying obligations or obtaining qualified review. Keep the conformity objective open for qualified assessment; no checklist or agent review certifies legal compliance.', 'organization; applicable regulations and standards', None),
 ('GES-IAM-004', 'Perform recurring compliance audits. Qualified review without a recurrence requirement or audit procedure is insufficient; define cadence through the target profile and retain audit scope, findings and date.', 'organization; recurring compliance audit', None),
 ('GES-IAM-004', 'Maintain documentation of compliance efforts, including the relevant assessment and remediation work. A single qualified review does not establish maintained records covering those efforts.', 'organization; maintained compliance records', None),
 ('GES-GOV-008', 'Implement comprehensive audit logging for all critical actions and access. The source covers critical actions beyond administrative actions; retention of whatever evidence happens to exist does not establish complete collection.', 'all critical actions and access; comprehensive collection', 'Original claim substitutes important access and administrative actions for all critical actions and access, narrowing the action class.'),
 ('GES-GOV-008', 'Audit logs must resist tampering, be securely stored and have RBAC. Controlled access alone does not establish role-based enforcement, secure storage or tamper protection; identify the integrity mechanism and access roles without inventing a guarantee.', 'audit artifacts; integrity, secure storage and role-based access', 'Original claim omits the explicit role-based access mechanism and secure-storage requirement.'),
 ('GES-GOV-008', 'Review audit logs regularly for anomalies. Investigating observed anomalies is downstream from scheduled log examination and cannot replace that examination.', 'audit logs; recurring anomaly review', 'Original claim omits the recurring cadence.'),
 (None, 'Verify or request data-protection practices from GitHub and other business systems. Keep the alternative of requesting evidence where verification is not yet possible; track unknown responses rather than certifying provider controls.', 'GitHub and other business systems; verify or request provider practices', 'Original claim changes verify-or-request into obtain-and-assess and narrows other systems to connected systems.'),
 (None, 'Use strong encryption algorithms together with key-management practices. Preserve strength assessment and the whole key lifecycle, rather than reducing management to key custody; qualified target decisions must specify suitable mechanisms.', 'protected data; strong encryption and key management', 'Original claim replaces strong algorithms with appropriate encryption and key management with key custody.'),
 (None, 'Test encryption mechanisms regularly for effectiveness. Configuration existence and a one-off exercise do not establish recurring effective protection; retain test scope, outcomes and recurrence.', 'encryption mechanisms; recurring effectiveness tests', 'Original claim omits recurrence and the explicit effectiveness outcome.'),
 ('GES-SEC-007', 'Develop and regularly update an incident-response plan. Defined owners and testing support response, but do not by themselves establish a maintained plan and regular revisions.', 'incident response; developed plan and recurring updates', 'Maintaining a current plan must retain actual development and recurring update duties.'),
 ('GES-SEC-007', 'Conduct incident-response drills regularly. Testing response procedures is related, but the recurring exercise cadence and drills must remain explicit.', 'incident response; recurring drills', 'Original claim omits regularity and the drill form.'),
 ('GES-SEC-007', 'Ensure every team member knows their incident-response role. Naming owners and escalation does not demonstrate awareness across all team members; retain role communication and awareness evidence.', 'all team members; awareness of incident-response roles', 'Original claim changes demonstrated all-team awareness into assignment and communication alone.'),
 ('GES-IAM-004', 'Provide regular compliance training for all team members. Security training and qualified compliance review are related but do not establish compliance curriculum, recurrence or the all-team audience.', 'all team members; recurring compliance training', 'Original claim omits all-team scope.'),
 ('GES-IAM-004', 'Include new regulations and standards in compliance training. Monitoring obligations or updating only generic guidance does not establish training content updates; retain applicable-obligation context without assuming every regulation applies.', 'compliance curriculum; new regulations and standards', None),
 ('GES-IAM-004', 'Track and document compliance-training completion. Qualified review does not replace participant completion records and documentation; distinguish delivery from completion.', 'compliance-training participants; completion tracking and documentation', None),
 ('GES-SEC-005', 'Conduct regular threat-modeling exercises to identify potential vulnerabilities. Architecture-change triggers alone miss recurring reassessment in a stable system; keep recurrence and vulnerability identification explicit.', 'software threats; recurring threat-modeling exercise', None),
 ('GES-SEC-005', 'Involve cross-functional teams in threat modeling. A technical inventory of assets and trust boundaries does not establish cross-functional participation; record the participating functions without imposing an invented roster.', 'cross-functional teams; threat-model participation', 'Relevant disciplines must not narrow the cross-functional-team participation requirement.'),
 ('GES-SEC-005', 'Update threat models for new threats and environmental changes. Updating after material system changes alone excludes new threat information and non-system environmental changes.', 'threat models; new threats and environmental changes', None),
 ('GES-SEC-010', 'Perform recurring penetration testing to identify and mitigate security weaknesses. Owner authorization is a local safety prerequisite, not upstream wording; planning relevant security testing is not proof of actual recurring penetration tests.', 'authorized testing scope; recurring penetration testing and mitigation', 'Original claim adds authorization appropriately but drops recurring performance and identification/mitigation outcomes.'),
 ('GES-SEC-010', 'Use both internal and external testers for comprehensive coverage. Considering two perspectives does not preserve actual use of both tester classes; retain this source recommendation and leave any capacity-based local exception explicit.', 'penetration testing; internal and external testers', 'Original claim weakens use both to consider perspectives and omits comprehensive coverage.'),
 ('GES-SEC-006', 'Address penetration-test findings promptly. Merely prioritizing confirmed findings is narrower than addressing findings; risk-based treatment and profile-defined response cadence must remain distinct from source recommendation strength.', 'penetration-test findings; prompt treatment', 'Original claim substitutes prioritization for addressing and inserts confirmed as a limiting qualifier.'),
 ('GES-SEC-006', 'Document and track penetration-test remediation efforts. Finding inventory and remediation-age metrics support tracking but do not establish the documented remediation actions and resulting evidence.', 'penetration-test remediation efforts; documentation and tracking', None),
 (None, 'Apply security patches and updates in a timely manner. Finding prioritization and dependency update configuration do not establish patch application across affected systems; define timeliness by target risk and preserve observed installation evidence.', 'software and hardware; timely security patch and update application', None),
 (None, 'Automate patch management where possible. Local authorization is necessary for execution, but possibility is not interchangeable with unrecorded preference; assess feasible automation and document constraints without silently making it optional.', 'patch management; automation where feasible and authorized', 'Original claim substitutes appropriate for possible and patching for the wider patch-management process.'),
 (None, 'Maintain an inventory of all software and hardware to track updates. Restricting the inventory to what is currently deemed needed can silently drop assets; preserve the all-assets denominator and update tracking.', 'all software and hardware; update-tracking inventory', 'Original claim narrows all software and hardware to the inventory deemed needed.'),
 ('GES-SEC-006', 'Implement a robust vulnerability-management program. A finding list with priorities does not establish the program roles, discovery, treatment and follow-up necessary to operate it; define robustness through reviewed procedures rather than an unsupported adjective.', 'applications and infrastructure; vulnerability-management program', None),
 ('GES-SEC-006', 'Scan applications and infrastructure regularly for vulnerabilities. A generic assessment or finding inventory does not establish scanner execution, recurrence or both target classes.', 'applications and infrastructure; recurring vulnerability scans', 'Original claim replaces scanning with broader assessment and can lose actual scan execution.'),
 ('GES-SEC-006', 'Prioritize and remediate identified vulnerabilities based on risk. Canonical prioritization and remediation-age measurement do not explicitly require remediation; retain actual treatment and documented accepted-risk alternatives.', 'identified vulnerabilities; risk-based prioritization and remediation', 'Original claim records ordering but omits actual remediation.'),
 ('GES-ARC-009', 'Deploy continuous security-monitoring tools that detect and respond to threats in real time. Alert routing and periodic tests do not establish continuous tooling or response capability; define real-time operational criteria per target without inventing a numeric guarantee.', 'security threats; continuous tooling, detection and real-time response', 'Original claim replaces continuous tools and real-time response with an unspecified operating model.'),
 ('GES-ARC-009', 'Configure alerts for suspicious activity. The canonical deployed-service applicability can miss security monitoring of non-service enterprise activity; retain that broader security scope and evidence of configured suspicious-activity alerts.', 'suspicious activity; configured security alerts', None),
 ('GES-ARC-009', 'Review and update monitoring configurations regularly. Testing alert delivery is related but does not establish configuration review and updating on a maintained cadence.', 'security monitoring configuration; recurring review and updates', 'Original claim omits review and recurrence.'),
 ('GES-SEC-009', 'Provide ongoing security training and awareness programs for all employees. Secure-development guidance and completion tracking do not establish delivered awareness programs, recurrence or employees outside development.', 'all employees; ongoing security training and awareness programs', 'Original claim narrows all employees to relevant personnel and omits awareness programs.'),
 ('GES-SEC-009', 'Include the latest security threats and best practices in training. Appropriate general guidance does not establish current threat coverage and best-practice curriculum updates.', 'security-training curriculum; current threats and best practices', 'Original claim omits best practices as a distinct curriculum component.'),
 ('GES-SEC-009', 'Track and document security-training completion. Completion tracking is in the draft objective, but retain documented evidence and the preceding all-employee program scope before consolidating this claim.', 'all employee training participants; completion tracking and documentation', None),
 ('GES-SEC-009', 'Conduct phishing simulations regularly to teach employees recognition of phishing attempts. Authorization is a local safety prerequisite; generic security education does not establish recurring simulations or the recognition-learning objective.', 'employees; authorized recurring phishing-recognition simulations', 'Original claim omits recurrence and employee recognition outcome, and inserts a relevance condition absent from the checklist.'),
 ('GES-SEC-009', 'Analyze simulation results and provide feedback to employees. Merely tracking course completion does not establish analysis and individualized or team feedback after exercises.', 'phishing-simulation results; analysis and employee feedback', None),
 ('GES-SEC-009', 'Adjust training based on phishing-simulation outcomes. Maintain a trace from observed exercise results to curriculum changes; general guidance maintenance does not demonstrate this feedback loop.', 'phishing-simulation findings; training adaptation', None),
 ('GES-SEC-009', 'Establish a security-champions program promoting security best practices within teams. Generic education does not establish a program, named champions or within-team support; preserve the source recommendation rather than reducing it to consideration.', 'teams; established security-champions program promoting best practices', 'Original claim weakens establish a program into consider a capability.'),
 ('GES-SEC-009', 'Provide security champions additional training and resources. Generic personnel training does not preserve the additional support targeted to champions or the separate resource provision.', 'security champions; additional training and resources', 'Original claim omits additional as a distinction from ordinary training.'),
 ('GES-SEC-009', 'Recognize and reward security-champion contributions. Recognition alone does not preserve the reward objective; local policy must decide suitable rewards without fabricating monetary commitments.', 'security champions; recognition and reward', 'Original claim omits rewards.'),
]
assert len(judgments) == 41
decisions, primary, drafts = [], [], []
for claim, (catalog_id, rationale, scope, fidelity) in zip(a['B']['claims'][18:59], judgments):
    n = int(claim['claim_id'].rsplit('-', 1)[1])
    proposal_id = f'GES-OPS-{n + 36:03d}'
    proposal = pi[proposal_id]
    assert proposal['sources'][0]['start_line'] == claim['start_line']
    subject = subjects[claim['claim_id']]['claim']
    refs = [{'id': proposal_id, 'revision': proposal['revision']}]
    if catalog_id:
        refs.insert(0, {'id': catalog_id, 'revision': ci[catalog_id]['revision']})
    decision = {'schema': 'ges.reconciliation-decision.v1', 'proposition_ids': [claim['claim_id']], 'disposition': 'SPECIALIZATION', 'source_treatment': 'RETAINED', 'control_references': refs, 'rationale': rationale, 'preserved_fields': [], 'lost_fields': [], 'conflicts': [], 'review': {'status': 'PROPOSED', 'reviewer': None, 'evidence_reference': None}}
    decision['id'] = stable_id(decision)
    validate_record(decision)
    decisions.append(decision)
    # Empty schema-level preserved/lost arrays make no completeness assertion.
    # Actual source distinctions are in the authored interpretation and scope.
    primary.append({'claim': subject, 'decision_id': decision['id'], 'primary_identity': 'codex:/root/source_worker_b', 'source_scope_and_distinctions': scope, 'interpretation': rationale, 'source_fidelity_defect': fidelity, 'source_span_sha256': sha('\n'.join(source['content'].splitlines()[claim['start_line']-1:claim['end_line']]).encode()), 'proposal_record_digest': digest(proposal), 'related_catalog_record_digest': digest(ci[catalog_id]) if catalog_id else None, 'status': 'SOURCE_BOUND_PROPOSAL_PENDING_D_A_E', 'original_claim_unchanged': True})
    drafts.append({'claim': subject, 'proposed_disposition': 'SPECIALIZE', 'control_references': [{'id': r['id'], 'revision': r['revision'], 'collection': 'CATALOG' if r['id'] in ci else 'PROPOSAL'} for r in refs], 'details': {'scope': scope, 'distinction': rationale}, 'rationale': rationale, 'accepted_policy': False, 'adopted_obligation': None, 'primary_reviewer': 'codex:/root/source_worker_b', 'status': 'PROPOSED_NOT_RECONCILIATION_RECEIPT', 'hold_for_source_fidelity_repair': fidelity is not None})

def write(name, value):
    (OUT / name).write_text(json.dumps(value, indent=2, sort_keys=True) + '\n')

write('proposed-decisions.json', decisions)
write('primary-review.json', primary)
write('draft-dispositions.json', drafts)
write('occurrence-crosswalk.json', [{**subjects[c['claim_id']], 'primary_review_status': 'REVIEWED_PROPOSED_TRANCHE_02'} for c in a['B']['claims'][18:59]])
write('residuals.json', {'tranche_claim_ids': [c['claim_id'] for c in a['B']['claims'][18:59]], 'tranche_primary_claim_count': 41, 'tranche_occurrence_count': 41, 'proposed_specializations': 41, 'source_fidelity_holds': [p['claim']['claim_id'] for p in primary if p['source_fidelity_defect']], 'proposed_map_count': 0, 'validated_reconciliation_receipts': 0, 'unreviewed_claim_ids_after_both_tranches': [c['claim_id'] for c in a['B']['claims'][59:]], 'unreviewed_claim_count_after_both_tranches': 103, 'boundaries': ['First packet immutable at 53d274be18bb5293685d14628b6d73b4a9476593.', 'All 41 decisions need D review, A reconciliation and E audit; no new mapping is counted.', 'Existing proposals remain quarantined with blank source hashes and unspecified applicability; references preserve candidate identity, not adoption.', 'Apparent repetition does not establish duplicate source claims without independent scope review.', 'No human approval, rights clearance, source completeness, policy acceptance or native implementation.']})
contexts = [('content/library/application-security/design-principles.md', 59, 181), ('content/library/application-security/recommendations/threat-model.md', 1, 230)]
write('input-bindings.json', {'primary_identity': 'codex:/root/source_worker_b', 'assignment_sha256': sha(assignment_path.read_bytes()), 'original_packet_crosswalk_sha256': sha(crosswalk_path.read_bytes()), 'baseline': a['baseline'], 'catalog_digest': digest(catalog), 'proposal_digest': digest(proposals), 'source_snapshot_compressed_sha256': sha(snapshot_path.read_bytes()), 'source_artifact_sha256': sha(source['content'].encode()), 'context_read_spans': [{'path': p, 'content_sha256': rows[p]['sha256'], 'start_line': start, 'end_line': end} for p, start, end in contexts], 'checklist_primary_scope': {'start_line': 47, 'end_line': 115}, 'context_limit': 'Threat-model reference inspected for source-integrity scope and method only. Its diagrams, remaining analysis, linked external framework and platform assertions are not independently certified.'})
write('packet-manifest.json', {'files': [{'path': p.name, 'sha256': sha(p.read_bytes())} for p in sorted(OUT.glob('*.json')) if p.name != 'packet-manifest.json'], 'decision_projection_digest': digest(decisions), 'primary_identity': 'codex:/root/source_worker_b', 'state': 'STAGED_PRIMARY_REVIEW_PENDING_D_A_E'})
print(json.dumps({'schema_valid_decisions': len(decisions), 'source_fidelity_holds': sum(bool(p['source_fidelity_defect']) for p in primary), 'decision_projection_digest': digest(decisions)}))
